import { createTheme, ThemeOptions } from '@mui/material/styles';

// Colores de GitHub para modo claro
const lightColors = {
  // Colores principales
  '--color-fg-default': '#24292f',
  '--color-fg-muted': '#656d76',
  '--color-fg-subtle': '#6e7781',
  '--color-canvas-default': '#ffffff',
  '--color-canvas-subtle': '#f6f8fa',
  '--color-border-default': '#d0d7de',
  '--color-border-muted': '#d0d7de',
  '--color-neutral-muted': '#f6f8fa',
  '--color-accent-fg': '#0969da',
  '--color-accent-emphasis': '#0969da',
  '--color-accent-muted': '#0969da',
  '--color-accent-subtle': '#ddf4ff',
  '--color-attention-fg': '#9a6700',
  '--color-attention-emphasis': '#9a6700',
  '--color-attention-muted': '#9a6700',
  '--color-attention-subtle': '#fff8c5',
  '--color-severe-fg': '#bc4c00',
  '--color-severe-emphasis': '#bc4c00',
  '--color-severe-muted': '#bc4c00',
  '--color-severe-subtle': '#ffebe9',
  '--color-danger-fg': '#cf222e',
  '--color-danger-emphasis': '#cf222e',
  '--color-danger-muted': '#cf222e',
  '--color-danger-subtle': '#ffebe9',
  '--color-success-fg': '#116329',
  '--color-success-emphasis': '#1a7f37',
  '--color-success-muted': '#1a7f37',
  '--color-success-subtle': '#dafbe1',
  '--color-done-fg': '#8250df',
  '--color-done-emphasis': '#8250df',
  '--color-done-muted': '#8250df',
  '--color-done-subtle': '#fbefff',
  '--color-open-fg': '#1a7f37',
  '--color-open-emphasis': '#1a7f37',
  '--color-open-muted': '#1a7f37',
  '--color-open-subtle': '#dafbe1',
  '--color-closed-fg': '#cf222e',
  '--color-closed-emphasis': '#cf222e',
  '--color-closed-muted': '#cf222e',
  '--color-closed-subtle': '#ffebe9',
  '--color-scale-black': '#010409',
  '--color-scale-white': '#ffffff',
  '--color-scale-gray-0': '#f6f8fa',
  '--color-scale-gray-1': '#f1f3f4',
  '--color-scale-gray-2': '#eef1f6',
  '--color-scale-gray-3': '#dde1e6',
  '--color-scale-gray-4': '#d0d7de',
  '--color-scale-gray-5': '#afb8c1',
  '--color-scale-gray-6': '#8c959f',
  '--color-scale-gray-7': '#6e7781',
  '--color-scale-gray-8': '#57606a',
  '--color-scale-gray-9': '#424a53',
  '--color-scale-blue-0': '#ddf4ff',
  '--color-scale-blue-1': '#b6e3ff',
  '--color-scale-blue-2': '#80ccff',
  '--color-scale-blue-3': '#54aeff',
  '--color-scale-blue-4': '#218bff',
  '--color-scale-blue-5': '#0969da',
  '--color-scale-blue-6': '#0550ae',
  '--color-scale-blue-7': '#033d8b',
  '--color-scale-blue-8': '#0a3069',
  '--color-scale-blue-9': '#002155',
  '--color-scale-green-0': '#dafbe1',
  '--color-scale-green-1': '#aceebb',
  '--color-scale-green-2': '#6fdd8b',
  '--color-scale-green-3': '#4ac26b',
  '--color-scale-green-4': '#2da44e',
  '--color-scale-green-5': '#1a7f37',
  '--color-scale-green-6': '#116329',
  '--color-scale-green-7': '#044f1e',
  '--color-scale-green-8': '#003d16',
  '--color-scale-green-9': '#002d11',
  '--color-scale-yellow-0': '#fff8c5',
  '--color-scale-yellow-1': '#fae17d',
  '--color-scale-yellow-2': '#eac54f',
  '--color-scale-yellow-3': '#d4a72c',
  '--color-scale-yellow-4': '#bf8700',
  '--color-scale-yellow-5': '#9a6700',
  '--color-scale-yellow-6': '#7d4e00',
  '--color-scale-yellow-7': '#633c01',
  '--color-scale-yellow-8': '#4d2c00',
  '--color-scale-yellow-9': '#3b2300',
  '--color-scale-orange-0': '#ffebe9',
  '--color-scale-orange-1': '#ffcecb',
  '--color-scale-orange-2': '#ffaba8',
  '--color-scale-orange-3': '#ff8182',
  '--color-scale-orange-4': '#fa4549',
  '--color-scale-orange-5': '#cf222e',
  '--color-scale-orange-6': '#a40e26',
  '--color-scale-orange-7': '#82071e',
  '--color-scale-orange-8': '#660018',
  '--color-scale-orange-9': '#4c0014',
  '--color-scale-red-0': '#ffebe9',
  '--color-scale-red-1': '#ffcecb',
  '--color-scale-red-2': '#ffaba8',
  '--color-scale-red-3': '#ff8182',
  '--color-scale-red-4': '#fa4549',
  '--color-scale-red-5': '#cf222e',
  '--color-scale-red-6': '#a40e26',
  '--color-scale-red-7': '#82071e',
  '--color-scale-red-8': '#660018',
  '--color-scale-red-9': '#4c0014',
  '--color-scale-purple-0': '#fbefff',
  '--color-scale-purple-1': '#ecd8ff',
  '--color-scale-purple-2': '#d8b9ff',
  '--color-scale-purple-3': '#c297ff',
  '--color-scale-purple-4': '#a475f9',
  '--color-scale-purple-5': '#8250df',
  '--color-scale-purple-6': '#6639ba',
  '--color-scale-purple-7': '#512a97',
  '--color-scale-purple-8': '#3e1f79',
  '--color-scale-purple-9': '#2e1461',
  '--color-scale-pink-0': '#ffeff7',
  '--color-scale-pink-1': '#ffd3eb',
  '--color-scale-pink-2': '#ffadda',
  '--color-scale-pink-3': '#ff80c8',
  '--color-scale-pink-4': '#e85aad',
  '--color-scale-pink-5': '#bf3989',
  '--color-scale-pink-6': '#99286e',
  '--color-scale-pink-7': '#772057',
  '--color-scale-pink-8': '#611a47',
  '--color-scale-pink-9': '#4d1836',
  '--color-scale-coral-0': '#fff0eb',
  '--color-scale-coral-1': '#ffd6cc',
  '--color-scale-coral-2': '#ffb4a1',
  '--color-scale-coral-3': '#fd8c73',
  '--color-scale-coral-4': '#ec6547',
  '--color-scale-coral-5': '#c4432b',
  '--color-scale-coral-6': '#9e2f1c',
  '--color-scale-coral-7': '#801f0e',
  '--color-scale-coral-8': '#691105',
  '--color-scale-coral-9': '#510901'
};

// Colores de GitHub para modo oscuro
const darkColors = {
  '--color-fg-default': '#f0f6fc',
  '--color-fg-muted': '#7d8590',
  '--color-fg-subtle': '#6e7681',
  '--color-canvas-default': '#0d1117',
  '--color-canvas-subtle': '#161b22',
  '--color-border-default': '#30363d',
  '--color-border-muted': '#21262d',
  '--color-neutral-muted': '#21262d',
  '--color-accent-fg': '#58a6ff',
  '--color-accent-emphasis': '#58a6ff',
  '--color-accent-muted': '#58a6ff',
  '--color-accent-subtle': '#1f6feb',
  '--color-attention-fg': '#d29922',
  '--color-attention-emphasis': '#d29922',
  '--color-attention-muted': '#d29922',
  '--color-attention-subtle': '#9e6a03',
  '--color-severe-fg': '#db6d28',
  '--color-severe-emphasis': '#db6d28',
  '--color-severe-muted': '#db6d28',
  '--color-severe-subtle': '#bd561d',
  '--color-danger-fg': '#f85149',
  '--color-danger-emphasis': '#f85149',
  '--color-danger-muted': '#f85149',
  '--color-danger-subtle': '#da3633',
  '--color-success-fg': '#3fb950',
  '--color-success-emphasis': '#3fb950',
  '--color-success-muted': '#3fb950',
  '--color-success-subtle': '#238636',
  '--color-done-fg': '#a371f7',
  '--color-done-emphasis': '#a371f7',
  '--color-done-muted': '#a371f7',
  '--color-done-subtle': '#8957e5',
  '--color-open-fg': '#3fb950',
  '--color-open-emphasis': '#3fb950',
  '--color-open-muted': '#3fb950',
  '--color-open-subtle': '#238636',
  '--color-closed-fg': '#f85149',
  '--color-closed-emphasis': '#f85149',
  '--color-closed-muted': '#f85149',
  '--color-closed-subtle': '#da3633',
  '--color-scale-black': '#010409',
  '--color-scale-white': '#ffffff',
  '--color-scale-gray-0': '#f0f6fc',
  '--color-scale-gray-1': '#c9d1d9',
  '--color-scale-gray-2': '#b1b7c0',
  '--color-scale-gray-3': '#8b949e',
  '--color-scale-gray-4': '#6e7681',
  '--color-scale-gray-5': '#484f58',
  '--color-scale-gray-6': '#30363d',
  '--color-scale-gray-7': '#21262d',
  '--color-scale-gray-8': '#161b22',
  '--color-scale-gray-9': '#0d1117',
  '--color-scale-blue-0': '#cae8ff',
  '--color-scale-blue-1': '#a5d6ff',
  '--color-scale-blue-2': '#79c0ff',
  '--color-scale-blue-3': '#58a6ff',
  '--color-scale-blue-4': '#388bfd',
  '--color-scale-blue-5': '#1f6feb',
  '--color-scale-blue-6': '#1158c7',
  '--color-scale-blue-7': '#0d419d',
  '--color-scale-blue-8': '#0c2d6b',
  '--color-scale-blue-9': '#051d4d',
  '--color-scale-green-0': '#aff5b4',
  '--color-scale-green-1': '#7ee787',
  '--color-scale-green-2': '#56d364',
  '--color-scale-green-3': '#3fb950',
  '--color-scale-green-4': '#2ea043',
  '--color-scale-green-5': '#238636',
  '--color-scale-green-6': '#196c2e',
  '--color-scale-green-7': '#0f5323',
  '--color-scale-green-8': '#033a16',
  '--color-scale-green-9': '#04260f',
  '--color-scale-yellow-0': '#f8e3a1',
  '--color-scale-yellow-1': '#f2cc60',
  '--color-scale-yellow-2': '#e3b341',
  '--color-scale-yellow-3': '#d29922',
  '--color-scale-yellow-4': '#bb8009',
  '--color-scale-yellow-5': '#9e6a03',
  '--color-scale-yellow-6': '#8a4f0c',
  '--color-scale-yellow-7': '#6e4400',
  '--color-scale-yellow-8': '#553300',
  '--color-scale-yellow-9': '#3d2400',
  '--color-scale-orange-0': '#ffc1a7',
  '--color-scale-orange-1': '#ffa198',
  '--color-scale-orange-2': '#ff7b72',
  '--color-scale-orange-3': '#f85149',
  '--color-scale-orange-4': '#da3633',
  '--color-scale-orange-5': '#c03126',
  '--color-scale-orange-6': '#a42523',
  '--color-scale-orange-7': '#8b1a1a',
  '--color-scale-orange-8': '#771212',
  '--color-scale-orange-9': '#5d0f0f',
  '--color-scale-red-0': '#ffc1a7',
  '--color-scale-red-1': '#ffa198',
  '--color-scale-red-2': '#ff7b72',
  '--color-scale-red-3': '#f85149',
  '--color-scale-red-4': '#da3633',
  '--color-scale-red-5': '#c03126',
  '--color-scale-red-6': '#a42523',
  '--color-scale-red-7': '#8b1a1a',
  '--color-scale-red-8': '#771212',
  '--color-scale-red-9': '#5d0f0f',
  '--color-scale-purple-0': '#e2c5ff',
  '--color-scale-purple-1': '#d2a8ff',
  '--color-scale-purple-2': '#bc8cff',
  '--color-scale-purple-3': '#a371f7',
  '--color-scale-purple-4': '#8957e5',
  '--color-scale-purple-5': '#6e40c9',
  '--color-scale-purple-6': '#5a32a3',
  '--color-scale-purple-7': '#4c2888',
  '--color-scale-purple-8': '#3a1d6e',
  '--color-scale-purple-9': '#2d1586',
  '--color-scale-pink-0': '#ffdaec',
  '--color-scale-pink-1': '#ffbedd',
  '--color-scale-pink-2': '#ff9bce',
  '--color-scale-pink-3': '#f778ba',
  '--color-scale-pink-4': '#db61a2',
  '--color-scale-pink-5': '#bf4b8a',
  '--color-scale-pink-6': '#9e3670',
  '--color-scale-pink-7': '#7d2457',
  '--color-scale-pink-8': '#5e103e',
  '--color-scale-pink-9': '#42062a',
  '--color-scale-coral-0': '#ffc1a7',
  '--color-scale-coral-1': '#ffa198',
  '--color-scale-coral-2': '#ff7b72',
  '--color-scale-coral-3': '#f85149',
  '--color-scale-coral-4': '#da3633',
  '--color-scale-coral-5': '#c03126',
  '--color-scale-coral-6': '#a42523',
  '--color-scale-coral-7': '#8b1a1a',
  '--color-scale-coral-8': '#771212',
  '--color-scale-coral-9': '#5d0f0f'
};

// Función para aplicar colores CSS al documento
export const applyColors = (isDark: boolean) => {
  const colors = isDark ? darkColors : lightColors;
  const root = document.documentElement;
  
  Object.entries(colors).forEach(([property, value]) => {
    root.style.setProperty(property, value);
  });
};

// Tema claro
export const lightTheme = createTheme({
  palette: {
    mode: 'light',
    primary: {
      main: '#0969da',
      light: '#58a6ff',
      dark: '#0550ae',
      contrastText: '#ffffff',
    },
    secondary: {
      main: '#656d76',
      light: '#8c959f',
      dark: '#424a53',
      contrastText: '#ffffff',
    },
    background: {
      default: '#ffffff',
      paper: '#f6f8fa',
    },
    text: {
      primary: '#24292f',
      secondary: '#656d76',
    },
    divider: '#d0d7de',
  },
  typography: {
    fontFamily: [
      '-apple-system',
      'BlinkMacSystemFont',
      '"Segoe UI"',
      '"Noto Sans"',
      'Helvetica',
      'Arial',
      'sans-serif',
      '"Apple Color Emoji"',
      '"Segoe UI Emoji"',
    ].join(','),
    h1: {
      fontSize: '2.5rem',
      fontWeight: 600,
      lineHeight: 1.25,
    },
    h2: {
      fontSize: '2rem',
      fontWeight: 600,
      lineHeight: 1.25,
    },
    h3: {
      fontSize: '1.5rem',
      fontWeight: 600,
      lineHeight: 1.25,
    },
    body1: {
      fontSize: '1rem',
      lineHeight: 1.5,
    },
    button: {
      textTransform: 'none',
      fontWeight: 500,
    },
  },
  shape: {
    borderRadius: 6,
  },
  components: {
    MuiButton: {
      styleOverrides: {
        root: {
          borderRadius: 6,
          padding: '8px 16px',
          fontSize: '14px',
          fontWeight: 500,
          textTransform: 'none',
          transition: 'all 0.2s ease-in-out',
          '&:hover': {
            filter: 'brightness(1.05)',
          },
          '&:active': {
            boxShadow: 'inset 0 1px 3px rgba(0,0,0,0.1)',
          },
        },
        contained: {
          boxShadow: 'none',
          '&:hover': {
            boxShadow: '0 1px 3px rgba(0,0,0,0.12)',
          },
        },
      },
    },
    MuiAppBar: {
      styleOverrides: {
        root: {
          backgroundColor: '#ffffff',
          color: '#24292f',
          boxShadow: '0 1px 3px rgba(0,0,0,0.12)',
        },
      },
    },
  },
} as ThemeOptions);

// Tema oscuro
export const darkTheme = createTheme({
  palette: {
    mode: 'dark',
    primary: {
      main: '#58a6ff',
      light: '#79c0ff',
      dark: '#1f6feb',
      contrastText: '#0d1117',
    },
    secondary: {
      main: '#7d8590',
      light: '#8c959f',
      dark: '#6e7681',
      contrastText: '#0d1117',
    },
    background: {
      default: '#0d1117',
      paper: '#161b22',
    },
    text: {
      primary: '#f0f6fc',
      secondary: '#7d8590',
    },
    divider: '#30363d',
  },
  typography: {
    fontFamily: [
      '-apple-system',
      'BlinkMacSystemFont',
      '"Segoe UI"',
      '"Noto Sans"',
      'Helvetica',
      'Arial',
      'sans-serif',
      '"Apple Color Emoji"',
      '"Segoe UI Emoji"',
    ].join(','),
    h1: {
      fontSize: '2.5rem',
      fontWeight: 600,
      lineHeight: 1.25,
    },
    h2: {
      fontSize: '2rem',
      fontWeight: 600,
      lineHeight: 1.25,
    },
    h3: {
      fontSize: '1.5rem',
      fontWeight: 600,
      lineHeight: 1.25,
    },
    body1: {
      fontSize: '1rem',
      lineHeight: 1.5,
    },
    button: {
      textTransform: 'none',
      fontWeight: 500,
    },
  },
  shape: {
    borderRadius: 6,
  },
  components: {
    MuiButton: {
      styleOverrides: {
        root: {
          borderRadius: 6,
          padding: '8px 16px',
          fontSize: '14px',
          fontWeight: 500,
          textTransform: 'none',
          transition: 'all 0.2s ease-in-out',
          '&:hover': {
            filter: 'brightness(1.05)',
          },
          '&:active': {
            boxShadow: 'inset 0 1px 3px rgba(0,0,0,0.3)',
          },
        },
        contained: {
          boxShadow: 'none',
          '&:hover': {
            boxShadow: '0 1px 3px rgba(0,0,0,0.3)',
          },
        },
      },
    },
    MuiAppBar: {
      styleOverrides: {
        root: {
          backgroundColor: '#161b22',
          color: '#f0f6fc',
          boxShadow: '0 1px 3px rgba(0,0,0,0.3)',
        },
      },
    },
  },
} as ThemeOptions); 